version: "3.7"

services:
#  app:
#    build:
#      context: .
#      dockerfile: Dockerfile
#    ports:
#      - 8080:8080
#    restart: unless-stopped
#    depends_on:
#      - db
#    networks:
#      - golang

  db:
    image: mongo:4.2
    restart: always
    ports:
      - 27017:27017
    networks:
      - golang

networks:
  golang: